"""
main.py - RAG Document Q&A Bot: Interactive CLI Chatbot

Provides a friendly command-line interface for asking questions
about your indexed PDF documents. Answers are generated by Gemini
and grounded strictly in the content of those documents.

Usage:
    python main.py
"""
import streamlit as st

st.title("RAG Document Q&A Bot")

from rag import answer_question


# ── Visual helpers ─────────────────────────────────────────────────────────────

DIVIDER  = "─" * 60
BOLD_DIV = "═" * 60

EXIT_COMMANDS = {"exit", "quit", "bye"}


def print_welcome() -> None:
    """Print the welcome banner shown at startup."""
    print()
    print(BOLD_DIV)
    print("  📚  RAG Document Q&A Bot")
    print("  Powered by Chroma · HuggingFace · Google Gemini")
    print(BOLD_DIV)
    print("  Ask any question about your indexed PDF documents.")
    print("  Type  'exit', 'quit', or 'bye'  to stop.\n")


def print_answer(result: dict) -> None:
    """
    Pretty-print the answer and source citations returned by answer_question().

    Args:
        result: Dict with keys 'answer' (str) and 'sources' (list of dicts).
    """
    print()
    print(DIVIDER)

    # ── Answer block ───────────────────────────────────────────────────────────
    print("🤖  Bot:")
    print()
    # Indent each line of the answer for visual clarity
    for line in result["answer"].splitlines():
        print(f"    {line}")

    # ── Sources block ──────────────────────────────────────────────────────────
    print()
    sources = result.get("sources", [])
    if sources:
        print("📚  Sources:")
        for s in sources:
            print(f"     • {s['source']}  (page {s['page']})")
    else:
        print("📚  Sources: none found in the indexed documents.")

    print(DIVIDER)
    print()


def print_goodbye() -> None:
    """Print the exit message."""
    print()
    print(BOLD_DIV)
    print("  👋  Goodbye! See you next time.")
    print(BOLD_DIV)
    print()


# ── Main chat loop ─────────────────────────────────────────────────────────────

def main() -> None:
    """
    Run the interactive Q&A loop.

    Continuously prompts the user for a question, retrieves relevant
    document chunks, and streams the grounded Gemini answer back to
    the terminal. Exits cleanly on 'exit', 'quit', or 'bye'.
    """
    print_welcome()

    while True:
        # ── Prompt user for input ──────────────────────────────────────────────
        try:
            user_input = input("👤  You: ").strip()
        except (EOFError, KeyboardInterrupt):
            # Handle Ctrl-D / Ctrl-C gracefully
            print_goodbye()
            break

        # ── Skip blank lines ───────────────────────────────────────────────────
        if not user_input:
            print("  ⚠️   Please type a question.\n")
            continue

        # ── Check for exit commands ────────────────────────────────────────────
        if user_input.lower() in EXIT_COMMANDS:
            print_goodbye()
            break

        # ── Call the RAG pipeline ──────────────────────────────────────────────
        print(f"\n  🔎  Searching documents …\n")
        try:
            result = answer_question(question=user_input, k=3)
            print_answer(result)

        except EnvironmentError as env_err:
            # Missing API key or other environment misconfiguration
            print(f"\n  ❌  Configuration error: {env_err}")
            print("  Check that GOOGLE_API_KEY is set in your .env file.\n")

        except Exception as err:
            # Catch-all for network errors, model errors, etc.
            print(f"\n  ❌  Something went wrong: {err}")
            print("  Please try again or rephrase your question.\n")


# ── Entry point ────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    main()